### ISSUE TITLE
GET /api/tech/post 수정 필요

### ISSUE THREAD

**Issue by JongHyeok-Park** [Seungkyu-Han/COBO_Tech_Blog_Server#58]
response에 아래 적힌 내용은 안 써서 삭제하시면 됩니다.

"fileIdUrlMap": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
"fileUrlIdMap": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
}

추가적으로 user 내용에 userId도 추가 부탁드립니다.

**Comment by Seungkyu-Han** [comment]
수정 완료했습니다
바로 서버에 반영시켜두고 issue는 닫겠습니다.
